# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=root
- name: mysql-user-pass
  literals:
  - username=root
  - password=root
- name: mysql-db-url
  literals:
  - database=polling_app
  - url=jdbc:mysql://mysql.atoken:3306/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - mysql-deployment.yaml
  - polling-app-server.yaml
  - polling-app-client.yaml  
